### ISSUE TITLE
doesent show qrcode

### ISSUE THREAD

**Issue by Link2Trials** [antonioribeiro/google2fa-qrcode#10]
i tried everything but on php 7.3.5 and 7.4.9 it doesent show the qrcode with this

$inlineUrl = $google2fa->getQRCodeInline(
    $companyName,
    $companyEmail,
    $secretKey
);

`<img src="<?php echo $inlineUrl;?>">`

**Comment by antonioribeiro** [comment]
Here's an running example you can use to start: https://phpsandbox.io/n/round-breeze-mzpk-pgrcn

**Comment by ahmed-raza** [comment]
Hi @antonioribeiro I am facing the exact same problem the qr image is not rendering at all. Can you please explain how to fix this?
<img width="239" alt="Screenshot 2022-10-06 at 3 56 57 PM" src="https://user-images.githubusercontent.com/8687215/194295987-be42de06-3e1a-48b2-b58b-1a58bef92a30.png">

**Comment by Link2Trials** [comment]
Hey the solution was in this post 

https://stackoverflow.com/questions/36716797/imagemagick-non-conforming-drawing-primitive-definition-error-draw-c-drawi 

It had to do wit the setLocale function from php

i removed the setlocale and it worked

**Comment by Link2Trials** [comment]
> Hi @antonioribeiro I am facing the exact same problem the qr image is not rendering at all. Can you please explain how to fix this?
> <img alt="Screenshot 2022-10-06 at 3 56 57 PM" width="239" src="https://user-images.githubusercontent.com/8687215/194295987-be42de06-3e1a-48b2-b58b-1a58bef92a30.png">

Hey the solution was in this post

https://stackoverflow.com/questions/36716797/imagemagick-non-conforming-drawing-primitive-definition-error-draw-c-drawi

It had to do wit the setLocale function from php

i removed the setlocale and it worked

**Comment by ahmed-raza** [comment]
Actually;
`$inlineUrl = $google2fa->getQRCodeInline(
    $companyName,
    $companyEmail,
    $secretKey
);`

Returns svg structure itself and not a url for <img src="{{ $inlineUrl }}" /> Which is causing the problem. Not sure how to fix this.

**Comment by Link2Trials** [comment]
> Actually; `$inlineUrl = $google2fa->getQRCodeInline( $companyName, $companyEmail, $secretKey );`
> 
> Returns svg structure itself and not a url for `<img src="{{ $inlineUrl }}" />` Which is causing the problem. Not sure how to fix this.

$inlineUrl = $google2fa->getQRCodeInline(
	    'Name',
	   $email,
	    $secret
	);

 <img src="<?php echo $inlineUrl;?>" alt="" />

this works when i remove the setLocale

**Comment by ahmed-raza** [comment]
Nevermind, I ended up rendering the svg structure as is.

**Comment by w5m** [comment]
> Actually; `$inlineUrl = $google2fa->getQRCodeInline( $companyName, $companyEmail, $secretKey );`
> 
> Returns svg structure itself and not a url for `<img src="{{ $inlineUrl }}" />` Which is causing the problem. Not sure how to fix this.

I encountered exactly the same issue (and can no longer view the example Antonio posted). The fix was two-fold...
1. Utilise a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) by prefixing the data (in this case, the generated SVG structure) with a MIME type to indicate what type of data will follow (i.e. `data:image/svg+xml;charset=utf-8,`).
2. Percent-encode (URL-encode) the data using the PHP [rawurlencode](https://www.php.net/manual/en/function.rawurlencode.php) function.

My final code looked like this and successfully rendered a QR Code in Chrome, Firefox and Edge...
`<img src="data:image/svg+xml;charset=utf-8,{{ rawurlencode($inlineUrl) }}" alt="QR Code for Two-Factor Authentication" />`

**Comment by peroln** [comment]
> > Actually; `$inlineUrl = $google2fa->getQRCodeInline( $companyName, $companyEmail, $secretKey );`
> > Returns svg structure itself and not a url for `<img src="{{ $inlineUrl }}" />` Which is causing the problem. Not sure how to fix this.
> 
> I encountered exactly the same issue @ahmed-raza (and can no longer view the example @antonioribeiro posted).
> 
> The fix was two-fold...
> 
> 1. Utilise a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs) by prefixing the data (in this case, the generated SVG structure) with a MIME type to indicate what type of data will follow (i.e. `data:image/svg+xml;charset=utf-8,`).
> 2. Percent-encode (URL-encode) the data using the PHP [rawurlencode](https://www.php.net/manual/en/function.rawurlencode.php) function.
> 
> My final code looked like this and successfully rendered a QR Code in Chrome, Firefox and Edge... `<img src="data:image/svg+xml;charset=utf-8,{{ rawurlencode($inlineUrl) }}" alt="QR Code for Two-Factor Authentication" />`

The problem was similar. Fixed it on your advice. Thanks
