### ISSUE TITLE
Please update changelog / release entries

### ISSUE THREAD

**Issue by mfn** [antonioribeiro/google2fa-qrcode#16]
Hello 👋 ,

thank you for your work on this package and the recent activities, this is very much appreciated 🙏 

Would you be so kind updating the CHANGELOG in the project and maybe also add some info to the releases at https://github.com/antonioribeiro/google2fa-qrcode/releases ?

thank you!

PS: maybe you can do this also for https://github.com/antonioribeiro/google2fa-laravel ? 🤔

**Comment by antonioribeiro** [comment]
Done. Not sure if I can still update the release notes, but will try to add them from now on. 
Thank you!

**Comment by mfn** [comment]
> Not sure if I can still update the release notes

Yes, as an admin/maintainer of a repo, the text can be edited anytime!

Thank you!
